name: Publish NPM Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --immutable --immutable-cache
      - run: yarn test
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: yarn install --immutable --immutable-cache
      - run: yarn npm publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
